# Generated by Django 3.2.17 on 2023-02-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('loaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_serial_num', models.CharField(max_length=10, unique=True)),
                ('reading_type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MpanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpan_core', models.IntegerField(unique=True)),
                ('validation_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_register_id', models.CharField(max_length=2)),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('method', models.CharField(max_length=1)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d0010.datafile')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d0010.meterdata')),
                ('mpan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d0010.mpandata')),
            ],
            options={
                'unique_together': {('mpan', 'meter', 'meter_register_id')},
            },
        ),
    ]
